name: Build Corne firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zmk-config
        uses: actions/checkout@v3
        with:
          path: zmk-config

      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install west dependencies
        run: pip install west

      - name: Initialize west
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export

      - name: Build left half
        run: |
          west build -s zmk/app -d build/left -b nice_nano_v2 \
            -- -DSHIELD=corne_left -DZMK_CONFIG=../zmk-config/config

      - name: Build right half
        run: |
          west build -s zmk/app -d build/right -b nice_nano_v2 \
            -- -DSHIELD=corne_right -DZMK_CONFIG=../zmk-config/config
